### ISSUE TITLE
Heap out of Memory on Newer Versions of Node

### ISSUE THREAD

**Issue by nevi-me** [itslenny/SymSpell.js#1]
Hey, I wanted to try out SymSpell.js, on node@6.7.0, but I remember that from a while ago, a hard limit was set on the JS heap size (can't remember if from v8 side or node). I keep getting 

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

when building the dictionary. Got any potential solutions?

**Comment by dongyuwei** [comment]
hi @nevi-me , I just tested this project with node v7.0.0 on my MBP(Retina, 15-inch, Early 2013, Memory 8 GB 1600 MHz DDR3) and v7.4.0 on my VPS(Ubuntu 14.04 with only 337 free memory), and it works.

for the low memory VPS server, I just built the dictionary on my MBP, store it in lmdb(with [node-lmdb](https://github.com/Venemo/node-lmdb)), then copy the preCalculated data to the VPS server, and `npm start` can start the test in very short time(36ms, consume only 28.5M memory).  

you can see my forked code here: https://github.com/dongyuwei/SymSpell.js/blob/master/dist/SymSpell.js

I just modify the JavaScript code(not the TypeScript code).

**Comment by dongyuwei** [comment]
Use `LMDB` or a `Trie`(I guess) to replace the `this.dictionary`(Dictionary that contains both the original words and the deletes derived from them) can reduce a large number of memory consumption.

**Comment by ldenoue** [comment]
do you have an implementation for WordSegmentation?
